/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  home: [
    'welcome',
    'productlist',
    'notice',
    'rock3/README',
    'rock4/products',
    'rock5/products',
    'rockpi/README',
    'compute-module/README',
    'zero/README',
    'nio/readme',
    'x/README',
    'sophon/README',
    'accessories/README',
    'compliance/README',
  ],
  rock3: [
    { type: "autogenerated", dirName: "rock3" }
  ],
  rock4: [
    { type: "autogenerated", dirName: "rock4" }
  ],
  rock5: [
    { type: "autogenerated", dirName: "rock5" }
  ],
  rockpi: [
    { type: "autogenerated", dirName: "rockpi" }
  ],
  accessories: [
    { type: "autogenerated", dirName: "accessories" }
  ],
  "compute-module": [
    { type: "autogenerated", dirName: "compute-module" }
  ],
  x: [
    { type: "autogenerated", dirName: "x" }
  ],
  zero: [
    { type: "autogenerated", dirName: "zero" }
  ],
  nio: [
    { type: "autogenerated", dirName: "nio" }
  ],
  sophon: [
    { type: "autogenerated", dirName: "sophon" }
  ],

  compliance: [
    { type: "autogenerated", dirName: "compliance" }
  ]
};

module.exports = sidebars;
