/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  home: [
    "welcome",
    "productlist",
    "notice",
    "rock2/products",
    "rock3/README",
    "rock4/products",
    "rock5/products",
    "rockpi/README",
    "som/README",
    "zero/README",
    "cubie/README",
    "nio/readme",
    "x/README",
    "fogwise/README",
    "e/README",
    "sirider/README",
    "orion/README",
    "accessories/README",
    "compliance/README",
    "roobi/README",
    "aicore/README",
    "dragon/README",
    "license",
  ],

  rock2: [{ type: "autogenerated", dirName: "rock2" }],
  rock3: [{ type: "autogenerated", dirName: "rock3" }],
  rock4: [{ type: "autogenerated", dirName: "rock4" }],
  rock5: [
    { type: "autogenerated", dirName: "rock5" },
    { type: "link", label: "ROOBI", href: "/roobi" },
  ],
  rockpi: [{ type: "autogenerated", dirName: "rockpi" }],
  accessories: [{ type: "autogenerated", dirName: "accessories" }],
  som: [{ type: "autogenerated", dirName: "som" }],
  x: [
    { type: "autogenerated", dirName: "x" },
    { type: "link", label: "ROOBI", href: "/roobi" },
  ],
  zero: [{ type: "autogenerated", dirName: "zero" }],
  cubie: [{ type: "autogenerated", dirName: "cubie" }],
  dragon: [{ type: "autogenerated", dirName: "dragon" }],
  aicore: [{ type: "autogenerated", dirName: "aicore" }],
  nio: [{ type: "autogenerated", dirName: "nio" }],
  fogwise: [{ type: "autogenerated", dirName: "fogwise" }],
  e: [{ type: "autogenerated", dirName: "e" }],
  sirider: [{ type: "autogenerated", dirName: "sirider" }],
  orion: [{ type: "autogenerated", dirName: "orion" }],
  compliance: [{ type: "autogenerated", dirName: "compliance" }],

  roobi: [{ type: "autogenerated", dirName: "roobi" }],
};

module.exports = sidebars;
